docs: Post hackathon updates
axelarnetwork/webdocs pull request #102
Opened 2022-03-29 19:01 UTC by ggutoski

Incorporate feedback after the hackathon.

## TODO

- [ ] Need docs for steps 2--3 of dev landing page: "Deploy your dapp to testnet or hacknet" @npty 
- [ ] Fancy buttons to highlight certain links on top landing page, dev landing page.
- [ ] Currently "resources" appears twice in sideboar: top level and inside developer role.  What's the best path here?

2022-03-30 13:37 UTC, sergeynog requested changes

2022-03-30 13:37 UTC, sergeynog commented on sidebars.js
>                  'roles/dev/explainers/cccc',
shall we keep it as "general message passing" and move the section out of explainers? it's one of the core pieces devs will need and minimize extra click.

2022-04-01 17:59 UTC, ggutoski commented on sidebars.js
>                  'roles/dev/explainers/cccc',
Done.  Can revisit later.

A reason to use the "explainer" headline is there's no code in this doc--it's only an explainer.  I wanted a title that clearly conveys that this document is nonessential if you're trying to get to code as fast as possible.  I think we'll want to revive the "explainer" section as the number of explainer docs grows.  But for now we have only this one so it doesn't matter.

2022-04-01 18:00 UTC, ggutoski commented
Cleaned up for quick deployment.  We still need to resolve the TODOs above.

2022-04-01 18:06 UTC, sergeynog approved these changes

2022-04-01 18:16 UTC, merged